### ISSUE TITLE
Compatibility with ns-3.42 version

### ISSUE THREAD

**Issue by geraldosarmento** [Orange-OpenSource/elora#1]
## Expected Behavior
No errors when building in ns-3.42 with ELoRa

## Actual Behavior
...contrib/elora/model/phy/lora-interference-helper.h:221:38: error: class template placeholder ‘ns3::EnumValue’ not permitted in this context
 221 |     void SetIsolationMatrixAttribute(EnumValue matrix);

## Steps to Reproduce the Problem

  1. ./ns3 build
  2.
  3.

## Specifications

  - ns-3 version: 3.42
  - lorawan module version: current at master
  - Platform: Linux Mint
  - Compiler: g++

**Comment by nondetalle** [comment]
Hi. As detailed in the [installation section of the README](https://github.com/Orange-OpenSource/elora/blob/469b9b30882d9a72ad902e945b683410f4ef7df6/README.md?plain=1#L34), currently `elora` only supports and has been tested on ns-3.40.

**Comment by nondetalle** [comment]
Hello, the code has been updated to support ns-3.42
